base_url = "https://example.com"
theme = "terminus"
title = "Xoxyi"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
katex = true
highlighting_style = "base16-ocean-dark"
